site_name: Izaki Dictionary
theme:
  name: material

nav:
  - Home: index.md
  - Dictionary: dictionary.md
  - Grammar:
      - Overview: grammar/overview.md
  - Tools:
      - Conjugator: tools/conjugator.md
      - Declension Guide: tools/declension.md
  - Byakuzhi:
      - Readings: byakuzhi/readings.md
      - Lookup: lookup.md
